//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Granda.ATTS.CIM.Data {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Granda.ATTS.CIM.Data.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   使用此强类型资源类，为所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 Alarm List Request 的本地化字符串。
        /// </summary>
        internal static string AMS_Alarm_List_Request {
            get {
                return ResourceManager.GetString("AMS_Alarm_List_Request", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Enable/Disable Alarms 的本地化字符串。
        /// </summary>
        internal static string AMS_Enable_Disable_Alarm {
            get {
                return ResourceManager.GetString("AMS_Enable_Disable_Alarm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Equipment Requests Time 的本地化字符串。
        /// </summary>
        internal static string CLKS_Equipment_Requests_Time {
            get {
                return ResourceManager.GetString("CLKS_Equipment_Requests_Time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Host Instructs Equipment to Set Time 的本地化字符串。
        /// </summary>
        internal static string CLKS_Host_Instructs_Time {
            get {
                return ResourceManager.GetString("CLKS_Host_Instructs_Time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Equipment reports Glass data or Lot data or Mask data for processed result 的本地化字符串。
        /// </summary>
        internal static string DCS_Discrete_Variable_Data_Send {
            get {
                return ResourceManager.GetString("DCS_Discrete_Variable_Data_Send", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Equipment Constants Change by Operator 的本地化字符串。
        /// </summary>
        internal static string DCS_Equipment_Constants_Change {
            get {
                return ResourceManager.GetString("DCS_Equipment_Constants_Change", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Host requests the new value of Equipment Constants Variables(ECV) 的本地化字符串。
        /// </summary>
        internal static string DCS_Equipment_Constants_Request {
            get {
                return ResourceManager.GetString("DCS_Equipment_Constants_Request", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Host Initiates Trace Report 的本地化字符串。
        /// </summary>
        internal static string DCS_Host_Initiates_Trace_Report {
            get {
                return ResourceManager.GetString("DCS_Host_Initiates_Trace_Report", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Host requests the formatted status 的本地化字符串。
        /// </summary>
        internal static string DCS_Host_request_Formatted_status {
            get {
                return ResourceManager.GetString("DCS_Host_request_Formatted_status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Host requests the value of Status Variables (SV) 的本地化字符串。
        /// </summary>
        internal static string DCS_Host_request_value_status {
            get {
                return ResourceManager.GetString("DCS_Host_request_value_status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Host requests Enable or Disable Events 的本地化字符串。
        /// </summary>
        internal static string DCS_Host_Requests_Enable_Disable_Event {
            get {
                return ResourceManager.GetString("DCS_Host_Requests_Enable_Disable_Event", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Host sends a muiti-block display message 的本地化字符串。
        /// </summary>
        internal static string ETSS_Host_Send {
            get {
                return ResourceManager.GetString("ETSS_Host_Send", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Operator sends information to host 的本地化字符串。
        /// </summary>
        internal static string ETSS_Operator_Send_Info {
            get {
                return ResourceManager.GetString("ETSS_Operator_Send_Info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Online Scenario (Offline -&gt; Online by Unit) 的本地化字符串。
        /// </summary>
        internal static string Intialize_Scenario_1 {
            get {
                return ResourceManager.GetString("Intialize_Scenario_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Offline Scenario (Online -&gt; Offline by Unit) 的本地化字符串。
        /// </summary>
        internal static string Intialize_Scenario_2 {
            get {
                return ResourceManager.GetString("Intialize_Scenario_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Online Scenario (Offline -&gt; Online by Host) 的本地化字符串。
        /// </summary>
        internal static string Intialize_Scenario_3 {
            get {
                return ResourceManager.GetString("Intialize_Scenario_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Offline Scenario (Online -&gt; Offline by Host) 的本地化字符串。
        /// </summary>
        internal static string Intialize_Scenario_4 {
            get {
                return ResourceManager.GetString("Intialize_Scenario_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Host Command-Abort 的本地化字符串。
        /// </summary>
        internal static string RCS_Host_Command_Abort {
            get {
                return ResourceManager.GetString("RCS_Host_Command_Abort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Host Command-Cancel 的本地化字符串。
        /// </summary>
        internal static string RCS_Host_Command_Cancel {
            get {
                return ResourceManager.GetString("RCS_Host_Command_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Host Command-Operator Call 的本地化字符串。
        /// </summary>
        internal static string RCS_Host_Command_Operator_Call {
            get {
                return ResourceManager.GetString("RCS_Host_Command_Operator_Call", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Host Command-Pause 的本地化字符串。
        /// </summary>
        internal static string RCS_Host_Command_Pause {
            get {
                return ResourceManager.GetString("RCS_Host_Command_Pause", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Host Command-Resume 的本地化字符串。
        /// </summary>
        internal static string RCS_Host_Command_Resume {
            get {
                return ResourceManager.GetString("RCS_Host_Command_Resume", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Host Command-Start 的本地化字符串。
        /// </summary>
        internal static string RCS_Host_Command_Start {
            get {
                return ResourceManager.GetString("RCS_Host_Command_Start", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Host Attempts to Process Program Directory Request 的本地化字符串。
        /// </summary>
        internal static string RMS_Host_Attempts_To_Recipe_Mnt {
            get {
                return ResourceManager.GetString("RMS_Host_Attempts_To_Recipe_Mnt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Process Program is changed(created/edited/deleted) by Operator 的本地化字符串。
        /// </summary>
        internal static string RMS_Recipe_Changed {
            get {
                return ResourceManager.GetString("RMS_Recipe_Changed", resourceCulture);
            }
        }
    }
}
